export default {
    army_beige: { name: 'army-beige', title: 'Army Beige', hex: '#DBC9B9' },
    army_brown: { name: 'army-brown', title: 'Army Brown', hex: '#796658' },
    ash_grey: { name: 'ash-grey', title: 'Ash Grey', hex: '#4C4E55' },
    charcoal_black: { name: 'black-charcoal', title: 'Charcoal Black', hex: '#000000' },
    cherry_red: { name: 'red-cherry', title: 'Cherry Red', hex: '#A04F4C' },
    cotton_white: { name: 'white-cotton', title: 'Cotton White', hex: '#FFFFFF' },
    cream: { name: 'cream', title: 'Cream', hex: '#EFDBAC' },
    earth_brown: { name: 'earth-brown', title: 'Earth Brown', hex: '#735D52' },
    e_sun_silver: { name: 'e-sun-silver', title: 'eSun Silver', hex: '#CED9E1' },
    grey_blue: { name: 'grey-blue', title: 'Grey Blue', hex: '#6A8CA9' },
    grey: { name: 'grey', title: 'Grey', hex: '#CBA47A' },
    light_blue: { name: 'blue-light', title: 'Light Blue', hex: '#4D94E0' },
    matte_light_gray: { name: 'grey-light-matte', title: 'Matte Light Grey', hex: '#D5DBE3' },
    matte_navy: { name: 'navy-matte', title: 'Matte Navy', hex: '#6C84AA' },
    matte_orange: { name: 'orange-matte', title: 'Matte Orange', hex: '#EE9037' },
    matte_terra_cotta: { name: 'matte-terra-cotta', title: 'Matte Terracotta', hex: '#DBADA6' },
    matte_wood_brown: { name: 'wood-brown-matte', title: 'Matte Wood Brown', hex: '#CBA47A' },
    military_green: { name: 'green-military', title: 'Military Green', hex: '#414639' },
    muted_green: { name: 'green-muted', title: 'Muted Green', hex: '#9CA694' },
    muted_white: { name: 'white-muted', title: 'Muted White', hex: '#FFFFFF' },
    pastel_ice: { name: 'pastel-ice', title: 'Pastel Ice', hex: '#BEDEED' },
    true_black: { name: 'black', title: 'Black', hex: '#000000' },
    true_gold: { name: 'gold', title: 'Gold', hex: '#F3D488' },
    true_green: { name: 'green', title: 'Green', hex: '#65A160' },
    true_orange: { name: 'orange', title: 'Orange', hex: '#ED9038' },
    true_red: { name: 'red', title: 'Red', hex: '#EA5B54' },
    true_yellow: { name: 'yellow', title: 'Yellow', hex: '#FFFF54' },
 };